### PR TITLE
Refresh without client secret

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Allow the refresh of tokens without the client_secret for the new fedcloud client

---

**Related issue :**

### CODE REVIEW

**Comment by gwarf** [comment]
Duh, an error on the opennebula part:

[](url)
Screenshot 2021-05-11 at 14 10 24

**Comment by enolfc** [comment]
> Duh, an error on the opennebula part:
> 

saw that a bit of a pain :(

**Comment by enolfc** [comment]
> > > Duh, an error on the opennebula part:
> > 
> > 
> > saw that a bit of a pain :(
> 
> So it's a bit weird to see the linter fail on this (I mean, it's a quite advanced linting check!). Looking around I saw mentions of updating/reinstalling cleanly six, but...

Should be ok now, just disabled mypy in that line, no need to get crazy on this one.

> If we think that our others tests are fine we can merge this.
> Any plan to decommission/drop the opennebula part?

honestly I think we are not paying much attention there so I think we should do something about it, either properly maintain it, or drop it. My preference since long was trying to split providers into different packages but that also requires work on the base.

**Review by gwarf — APPROVED** [review]
LGTM

**Pull request merged**
